name: Cypress Tests

on:
  schedule:
    # Run regression tests every Monday at 2 AM EST (7 AM UTC)
    - cron: '0 7 * * 1'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'regression'
        type: choice
        options:
        - smoke
        - regression

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
    
    name: Cypress Tests (${{ matrix.browser }}) - ${{ github.event_name == 'schedule' && 'regression' || github.event.inputs.test_type }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: ${{ matrix.browser }}
        spec: cypress/e2e/**/*.feature
        record: false

    - name: Generate Mochawesome HTML report
      run: npm run posttest

    - name: List results directory
      run: ls -lR cypress/results || echo "No results directory"

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots-${{ matrix.browser }}-${{ github.event_name == 'schedule' && 'regression' || github.event.inputs.test_type }}
        path: cypress/screenshots
        if-no-files-found: ignore

    - name: Upload videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos-${{ matrix.browser }}-${{ github.event_name == 'schedule' && 'regression' || github.event.inputs.test_type }}
        path: cypress/videos
        if-no-files-found: ignore

    - name: Upload Mochawesome HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mochawesome-report-${{ matrix.browser }}
        path: cypress/results/mochawesome-report
        if-no-files-found: ignore
        retention-days: 2

    - name: Post Test Results Summary
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: |
        echo "## Cypress Test Results" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "[View Test Artifacts](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY 